### PR TITLE
Leaderboard: setup project

### PR DESCRIPTION
**Pull request by Fombi-Favour**
In this activity, we:
- Added linter files
- Added webpack dependencies
- Added `src` folder for the design
- Added `dist` folder as result

## Issue
proof

### CODE REVIEW

**Review by mukhammadrizooff — COMMENTED** [review]
Hi @Fombi-Favour, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that linters don't pass, kindly fix it 🙏🏼 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Fombi-Favour** [comment]
I mentioned the issue about the webhint linter in my pull request description.
Please consider my request 🙏

**Comment by Fombi-Favour** [comment]
Please I made a complain in the pull request description.
Please consider my request 🙏 🙏

**Review by AbelG101 — COMMENTED** [review]
# Hi @Fombi-Favour 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] Hello Favour, I think there's been some confusion as part of the project requirements you have to follow the proper GitFlow which means you'll have to create a new branch called `dev` or `development` and then make that branch the main branch of this repo in the settings. This way whenever you make a PR the merge request will be from your `feature` branch to the `dev` branch and not to the `main` branch as you have now. 
    - Refer to this [article for more info](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Fombi-Favour** [comment]
Please I don't understand

**Pull request closed without merging**
